service: Schedule


provider:
  name: aws
  region: us-east-2
  stage: DEV
  runtime: nodejs10.x
  role: arn:aws:iam::556332110707:role/LambdaBasicPrivileges
  environment: ${self:custom.environments.${opt:stage, 'DEV'}}

custom:
  saasName: 'Schedule'
  accessKeyId: ${ssm:concise-accessKeyId~true}
  secretAccessKey: ${ssm:concise-secretAccessKey~true}
  region: ${ssm:concise-region~true}
  pathToHandler: "compiled/src"
  pathToJSFile: "src"
  environments:
    DEV:
      saasName: ${self:custom.saasName}
      stage: 'DEV'
      accessKeyId: ${self:custom.accessKeyId}
      secretAccessKey: ${self:custom.secretAccessKey}
      region: ${self:custom.region}
    PROD:
      saasName: ${self:custom.saasName}
      stage: 'PROD'
      accessKeyId: ${self:custom.accessKeyId}
      secretAccessKey: ${self:custom.secretAccessKey}
      region: ${self:custom.region}



plugins:
  - serverless-plugin-include-dependencies


package:
  individually: true
  exclude:
    - "*.*"
    - "src/**"
    - "compiled/**"
    - "correctModuleNames.js"
  include:
    - "*.js"



functions:

  update:
    handler: ${self:custom.pathToHandler}/update.handler
    package:
      include:
      - "${self:custom.pathToJSFile}/update.js"
    events:
      - http:
          path: update
          method: put
          cors: true
    timeout: 30 # optional, in seconds, default is 6, if attached to API Gateway limited to 30
    tags:
      type: api


  get-boundTo:
    handler: ${self:custom.pathToHandler}/get-boundTo.handler
    package:
      include:
      - "${self:custom.pathToJSFile}/get-boundTo.js"
    events:
      - http:
          path: get-boundTo
          method: put
          cors: true
    timeout: 30 # optional, in seconds, default is 6, if attached to API Gateway limited to 30
    tags:
      type: api


  check:
    handler: ${self:custom.pathToHandler}/check.handler
    package:
      include:
      - "${self:custom.pathToJSFile}/update.js"
    events:
      - schedule: rate(5 minutes)
    timeout: 180 # optional, in seconds, default is 6, if attached to API Gateway limited to 30
